MOOC/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :comments
  resources :lectures do
    member do
      put "like", to: "lectures#upvote"
      put "dislike", to: "lectures#downvote"
      put :add_to_spam
      put :delete_from_spam
    end
  	resources :comments
  end
  resources :courses
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'courses#index'

end

MOOC/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  belongs_to :user
  belongs_to :course
  acts_as_votable
  has_many :comments
  has_and_belongs_to_many :users
end

MOOC/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy, :delete_from_spam, :add_to_spam]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
    @comments = Comment.where(lecture_id: @lecture).order("created_at DESC")
    # You can set the variable in the if-clause
    # And you also need to use static finders with a hash as an argument in Rails4
    # if (@user = User.find_by(name: params[:id]))
    #    @comments = @comments.lecture_id.all
      #  @logs = @user.logs.all
    # You don't need to call render explicitly
    # if you render the view with the same name as the action
    #  else
    #    render file: 'public/404', status: 404, formats: [html]
    #  end
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.user_id= current_user.id
    # @lecture.course_id =(ezai b2a a3ml save ll course id)
    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_by current_user
    redirect_to :back
  end

  def add_to_spam
    current_user.lectures << @lecture
    current_user.save

    redirect_to lectures_path
  end
  def delete_from_spam
    current_user.lectures.delete(@lecture)
    current_user.save

    redirect_to lectures_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:attachment, :content, :user_id, :course_id)
    end
end

MOOC/app/helpers/lectures_helper.rb
module LecturesHelper
end

MOOC/app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field" class="form-group">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>

  <div class="field" class="form-group">
    <%= f.label :content %><br>
    <%= f.cktext_area :content %>
  </div>
  <div class="field" class="form-group">
    <%= f.label :user_id %><br>
    <%= current_user.try(:name) %>
    <!-- <%= f.text_field :user_id %> -->
  <div class="field" class="form-group">
    <%= f.label :course_id %><br>
    <%= f.collection_select :course_id, Course.all, :id, :title %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MOOC/app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

MOOC/app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lectures</h1>

<table class="table">
  <thead>
    <tr>
      <th>Attachment</th>
      <th>Content</th>
      <th>User</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
    <div class="content-section-a alert alert-info">

        <div class="container">
          <div class="row">
              <div class="col-lg-5 col-sm-6">
                <div class="clearfix"></div>
                <h1 class="section-heading"><%= link_to lecture.content, lecture %></h1><br>
                <p class="lead">
                  Submitted <%= time_ago_in_words(lecture.created_at) %>
                  by <%= lecture.user_id %>
                </p>
              </div>

              <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <div class="btn btn-primary btn-lg" >
                  <%= link_to like_lecture_path(lecture), method: :put do %>
                    Upvote
                    <%= lecture.get_upvotes.size %>
                  <% end %>
                </div>
                <div class="btn btn-primary btn-lg" >
                  <%= link_to dislike_lecture_path(lecture), method: :put do %>
                    Downvote
                    <%= lecture.get_downvotes.size %>
                  <% end %>
                </div>
              </div>
          </div>
    </div>
  </div>
      <tr>
        <td><%= lecture.attachment %></td>
        <td><%= raw lecture.content %></td>
        <td><%= lecture.try(:user).try(:name)%></td>
        <td><%= lecture.try(:course).try(:title) %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>


      <% if current_user %>
              <% unless current_user.lectures.include?(lecture) %>
              <td target="_blank">
                <%= link_to 'Mark as Spam', add_to_spam_lecture_path(lecture), method: :put %>
              </td>
              <% end %>
            <% end %>
            <% if current_user %>
              <% if current_user.lectures.include?(lecture) %>
              <td target="_blank">
                <%= link_to 'unSpam', delete_from_spam_lecture_path(lecture), method: :put %>
              </td>
              <% end %>
            <% end %>

    <% end %>
  </tbody>
</table >

<br>

<%= link_to 'New Lecture', new_lecture_path %>

MOOC/app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

MOOC/app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-group">
  <strong>Attachment:</strong>
  <%= @lecture.attachment %>
</div>

<div class="form-group">
  <strong>Content:</strong>
  <%= raw @lecture.content %>
</div>

<div class="form-group">
  <strong>User:</strong>
  <%= @lecture.try(:user).try(:name) %>
</div>

<div class="form-group">
  <strong>Course:</strong>
  <%= @lecture.course_id %>

</div>
<%= render 'comments/showallcom' %>
<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>