MOOC/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :comments
  resources :lectures do
    member do
      put "like", to: "lectures#upvote"
      put "dislike", to: "lectures#downvote"
      put :add_to_spam
      put :delete_from_spam
    end
  	resources :comments
  end
  resources :courses
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'courses#index'

end

MOOC/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MOOC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!--bootstrap Template-->
    <link href="https://blackrockdigital.github.io/startbootstrap-landing-page/css/landing-page.css" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css " rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">


    <!-- online bootstrap -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
  <!-- ******************* Navigation **************************-->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'MOOC',courses_path, :class => 'navbar-brand topnav' %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <p class="navbar-text pull-right">
                <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.email %></strong>.
                  <%= link_to 'Courses',courses_path, :class => 'navbar-link' %>|
                  <%= link_to 'Lectures',lectures_path, :class => 'navbar-link' %>|
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                <% else %>
                  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                <% end %>
                </p>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<!--******************* EndOfNavigation ********************************-->


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<ul class="nav">
  <li class="active"><a href="/users">Users</a></li>
</ul>

<%= yield %>




<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="copyright text-muted small">Copyright &copy; MOOC teamwork. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>


</body>
</html>